### ISSUE TITLE
Incompatible with Remote Development

### ISSUE THREAD

**Issue by abhibeckert** [EugeneDae/vscode-refresh-browser#4]
When I try to run this extension while connected to a server with the Remote Development extension, it shows a message "An Error Occurred".

I think it's running on the remote server, instead of locally, which should be fixed by simply adding `"extensionKind": ["ui"]` to `package.json`

**Comment by EugeneDae** [comment]
Thanks! Fixed and published:
https://marketplace.visualstudio.com/items?itemName=dae.vscode-refresh-browser
